# Generated by Django 4.2.11 on 2024-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(default="f", max_length=180),
            preserve_default=False,
        ),
    ]
