# Generated by Django 4.2.11 on 2024-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
