# Generated by Django 5.0.3 on 2024-03-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='ai_request',
        ),
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.DeleteModel(
            name='AIRequest',
        ),
        migrations.DeleteModel(
            name='AIResponse',
        ),
        migrations.AddIndex(
            model_name='aichat',
            index=models.Index(fields=['request', 'response'], name='exam_prepar_request_85a187_idx'),
        ),
    ]
