# Generated by Django 5.0.3 on 2024-03-24 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_preparation', '0002_remove_airesponse_ai_request_aichat_delete_airequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('kind', models.CharField(choices=[('CHAT', 'Чат'), ('prepared_question', 'Подготовленные вопросы')], default='CHAT', max_length=320)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.DeleteModel(
            name='AIChat',
        ),
        migrations.AddIndex(
            model_name='aigenerated',
            index=models.Index(fields=['request', 'response'], name='exam_prepar_request_bd2675_idx'),
        ),
    ]
